services:
  server:
    image: gitea/gitea:${gitea_version:-ERROR}
    environment:
      - USER_UID=${GITEA_UID}
      - USER_GID=${GITEA_GID}
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
    restart: unless-stopped
    volumes:
      - ./volumes/gitea:/data
      - ./config/gitea/etc/timezone:/etc/timezone:ro
      - ./config/gitea/etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "127.0.0.1:22:22"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gitea_network
    healthcheck:
      test: >
        curl -fSs http://127.0.0.1:3000/api/healthz
        || grep '^  "status": "pass"'
        || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:${postgres_version:-ERROR}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - gitea_network
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=${POSTGRES_USER}", "PGPASSWORD=${POSTGRES_PASSWORD}", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gitea_network:
    # Explicit configuration of IPAM against use of collisions with
    # internal 10.x.y.z IPs.
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
